version: "3.7"

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB={!!!!!!!!!!!!!!!!}
    env_file:
      - .env
    ports:
      - "5433:5432"
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - /var/certbot/conf:/etc/letsencrypt/:rw
      - certbot_challenges:/var/www/.well-known/acme-challenge
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/app/nginx/
      - /var/www/static/:/var/www/static/
      - /var/certbot/conf:/etc/letsencrypt/:ro
      - certbot_challenges:/var/www/.well-known/acme-challenge
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
  media_volume:
  var:
  certbot_challenges:
